# Generated by Django 5.0.6 on 2024-05-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frizerie", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Frizer",
            new_name="Frizerie",
        ),
    ]
