# Generated by Django 5.0.6 on 2024-05-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coafor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coafor",
            name="description",
        ),
    ]
