# Generated by Django 5.0.6 on 2024-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coafor", "0002_remove_coafor_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coafor",
            name="full_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="coafor",
            name="notes",
            field=models.TextField(max_length=400),
        ),
    ]
